spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/security_db"
    username: "postgres"
    password: "domenisteve@gmail.com"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true