spring:
  datasource:
    url: "jdbc:h2:mem:security_db"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security=TRACE:
domeni:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:mySecretKeysForGeneratedToken1234567890}
      expiration-time: ${JWT_EXPIRATION-TIME:300000}
